# Generated by Django 3.0.3 on 2020-06-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='module_name',
            field=models.CharField(blank=True, choices=[('Monitoring HQ', 'Monitoring Hq'), ('Enugu Office', 'Enugu Office'), ('Lagos Office', 'Lagos Office'), ('Abuja Office', 'Abuja Office'), ('Registrars Office', 'CEO'), ('Accounts HQ', 'FAH')], max_length=20),
        ),
    ]
