# Generated by Django 3.0.3 on 2021-04-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='module_name',
            field=models.CharField(blank=True, choices=[('Monitoring HQ', 'Monitoring Hq'), ('Enugu Office', 'Enugu Office'), ('Lagos Office', 'Lagos Office'), ('Abuja Office', 'Abuja Office'), ('Asaba Office', 'Asaba Office'), ('Calabar Office', 'Calabar Office'), ('Port Harcourt Office', 'Port Harcourt Office'), ('Kano Office', 'Kano Office'), ('Registrars Office', 'CEO'), ('Accounts HQ', 'FAH')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Monitoring', 'Monitoring'), ('Zonal Offices', 'Zonal Offices'), ('Registrar', 'Registrar'), ('Finance', 'Finance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
