# Generated by Django 3.0.3 on 2022-05-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220507_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='application_status',
            field=models.IntegerField(default=1),
        ),
    ]
