# Generated by Django 3.0.3 on 2024-11-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_hospital_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='module_name',
            field=models.CharField(blank=True, choices=[('Monitoring HQ', 'Monitoring Hq'), ('Lagos Office', 'Lagos Office'), ('Enugu Office', 'Enugu Office'), ('Sokoto Office', 'Sokoto Office'), ('Abuja Office', 'Abuja Office'), ('Kano Office', 'Kano Office'), ('Port Harcourt Office', 'Port Harcourt Office'), ('Awka Office', 'Awka Office'), ('Calabar Office', 'Calabar Office'), ('Ilesha Office', 'Ilesha Office'), ('Maiduguri Office', 'Maiduguri Office'), ('Registrars Office', 'CEO'), ('Accounts HQ', 'FAH')], max_length=100),
        ),
    ]
