from django.urls import path
from django.shortcuts import render
from . import views

from .views import (
    StartNewRadApplication,
    StartGovInternshipApplication,
    StartPriInternshipApplication,
    StartRadiographyLicenseRenewal,
    StartGovInternshipRenewal,
    StartPriInternshipRenewal,
    StartRadiographyLicenseRenewalDetails,
    StartApplication,
    RegisterFacility,  
    HospitalDetailView,
    PrivateHospitalDetailView,
    FacilityDetailView,
    #PaymentListView,
    GenerateInvoiceView,
    GenerateRenewalInvoice,
    GenerateAccreditationInvoice,
    GenerateAccreditationPaymentDetails,
    PayAccreditationFee,
    PaymentCreateView,
    RenewalPaymentCreateView,
    PaymentDetailView,
    RenewalPaymentDetailView,
    PaymentProcessing,
    PaymentVerificationsView,
    AccreditationPaymentVerifications,
    PaymentConfirmation,
    PaymentVerificationListView,
    LicenseVerificationsSuccessful,
    AccreditationVerificationsSuccessful,
    ScheduleListView,
    ScheduleDetailView,
    InspectionListView,
    InspectionView,
    AppraisalView,
    InspectionApprovedView,
    AccreditationInspectionApprovedView,
    MyLicensesListView,
    MyLicensesDetailView,
    DownloadLicense,
    MyApplicationListView,
    MyLicenseApplicationsHistory,
    LicenseIssuanceView,
    PracticePermitRenewalFinalApproval,
    InternshipLicenseIssuanceView,
    StartLicenseRenewal,
    StartNewApplication,
    HospitalRenewView,
)



app_name = 'hospitals'


urlpatterns = [
    path('', views.hospitals_dashboard, name='hospitals_dashboard'),
    path('application_list/', MyApplicationListView.as_view(), name='application_list'),
    path('start_new_application/', StartNewApplication.as_view(), name='start_new_application'),
    path('<uuid:pk>/start_new_radiography_license_application/', StartNewRadApplication.as_view(), name='start_new_radiography_license_application'),
    path('<uuid:pk>/start_gov_internship_accreditation_application/', StartGovInternshipApplication.as_view(), name='start_gov_internship_accreditation_application'),
    path('<uuid:pk>/start_pri_internship_accreditation_application/', StartPriInternshipApplication.as_view(), name='start_pri_internship_accreditation_application'),
    path('<uuid:pk>/start_radiography_license_renewal/', StartRadiographyLicenseRenewal.as_view(), name='start_radiography_license_renewal'),
    path('<uuid:pk>/start_gov_internship_renewal/', StartGovInternshipRenewal.as_view(), name='start_gov_internship_renewal'),
    path('<uuid:pk>/start_pri_internship_renewal/', StartPriInternshipRenewal.as_view(), name='start_pri_internship_renewal'),
    path('<uuid:pk>/start_application/', StartApplication.as_view(), name='start_application'),
    path('<uuid:id>/hospital_details/', HospitalDetailView.as_view(), name='hospital_details'),
    path('<uuid:id>/private_hospital_details/', PrivateHospitalDetailView.as_view(), name='private_hospital_details'),
    path('<uuid:id>/start_radiography_license_renewal_details/', StartRadiographyLicenseRenewalDetails.as_view(), name='start_radiography_license_renewal_details'),
    path('<uuid:id>/facility_details/', FacilityDetailView.as_view(), name='facility_details'),
    path('<uuid:pk>/generate_invoice/', GenerateInvoiceView.as_view(), name='generate_invoice'),
    path('<uuid:pk>/generate_renewal_invoice/', GenerateRenewalInvoice.as_view(), name='generate_renewal_invoice'),
    path('<uuid:pk>/generate_accreditation_invoice/', GenerateAccreditationInvoice.as_view(), name='generate_accreditation_invoice'),
    path('<uuid:pk>/generate_accreditation_payment_details/', GenerateAccreditationPaymentDetails.as_view(), name='generate_accreditation_payment_details'),
    path('<uuid:pk>/pay_accreditation_fee/', PayAccreditationFee.as_view(), name='pay_accreditation_fee'),
    #path('payment_table/', PaymentListView.as_view(), name='payment_table'),
    path('<uuid:pk>/payment_processing/', PaymentCreateView.as_view(), name='payment_processing'),
    path('<uuid:pk>/renewal_payment_processing/', RenewalPaymentCreateView.as_view(), name='renewal_payment_processing'),
    path('<uuid:pk>/payment_transaction/', PaymentProcessing.as_view(), name='payment_transaction'),
    path('<uuid:id>/payment_details/', PaymentDetailView.as_view(), name='payment_details'),
    path('<uuid:id>/renewal_payment_details/', RenewalPaymentDetailView.as_view(), name='renewal_payment_details'),
    path('<uuid:pk>/payment_verifications/', PaymentVerificationsView.as_view(), name='payment_verifications'),
    path('<uuid:pk>/accreditation_payment_verifications/', AccreditationPaymentVerifications.as_view(), name='accreditation_payment_verifications'),
    path('<uuid:pk>/license_verifications_successful/', LicenseVerificationsSuccessful.as_view(), name='license_verifications_successful'),
    path('<uuid:pk>/accreditation_verifications_successful/', AccreditationVerificationsSuccessful.as_view(), name='accreditation_verifications_successful'),
    path('<uuid:pk>/schedule_detail/', ScheduleDetailView.as_view(), name='schedule_detail'),
    path('<uuid:pk>/inspection_processing/', InspectionView.as_view(), name='inspection_processing'),
    path('<uuid:pk>/appraisal_processing/', AppraisalView.as_view(), name='appraisal_processing'),
    path('<uuid:pk>/inspection_passed/', InspectionApprovedView.as_view(), name='inspection_passed'),
    path('<uuid:pk>/appraisal_passed/', AccreditationInspectionApprovedView.as_view(), name='appraisal_passed'),
    path('<uuid:pk>/license_issuance/', LicenseIssuanceView.as_view(), name='license_issuance'),
    path('<uuid:pk>/practice_permit_renewal_final_approval/', PracticePermitRenewalFinalApproval.as_view(), name='practice_permit_renewal_final_approval'),
    path('<uuid:pk>/internship_license_issuance/', InternshipLicenseIssuanceView.as_view(), name='internship_license_issuance'),
    path('<uuid:pk>/license_details/', MyLicensesDetailView.as_view(), name='license_details'),
    path('license_history/', MyLicenseApplicationsHistory.as_view(), name='license_history'),
    path('<uuid:pk>/start_renewal/', StartLicenseRenewal.as_view(), name='start_renewal'),
    path('hospital_renewal/', HospitalRenewView.as_view(), name='hospital_renewal'),
    path('start_registration/', RegisterFacility.as_view(), name='start_registration'),
    path('<uuid:id>/payment_confirmation/', PaymentConfirmation.as_view(), name='payment_confirmation'),
    path('payment_verified_table/', PaymentVerificationListView.as_view(), name='payment_verified_table'),
    path('schedule_table/', ScheduleListView.as_view(), name='schedule_table'),
    path('inspection_table/', InspectionListView.as_view(), name='inspection_table'),
    path('licenses_list/', MyLicensesListView.as_view(), name='licenses_list'),
    path('<uuid:id>/license_download/', DownloadLicense.as_view(), name='license_download'),
    path('<uuid:id>/download_rad_cert_reg/', views.download_rad_cert_reg, name='download_rad_cert_reg'),
    path('<uuid:id>/download_rad_practice_permit/', views.download_rad_practice_permit, name='download_rad_practice_permit'),
    path('<uuid:id>/download_accreditation_cert/', views.download_accreditation_cert, name='download_accreditation_cert'),
    path('lookup/', views.lookup, name='hospitals_lookup'),
    #path('start_application/<uuid:id>/', views.StartApplication, name="start_application"), 
    
]
