# Generated by Django 3.0.3 on 2022-05-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_accreditationlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccreditationList',
            new_name='InternshipList',
        ),
    ]
