# Generated by Django 3.0.3 on 2022-05-03 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_auto_20220503_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='DocumentUpload',
        ),
        migrations.AlterField(
            model_name='internshiplist',
            name='file',
            field=models.FileField(upload_to='internship_list/'),
        ),
    ]
