# Generated by Django 3.0.3 on 2020-09-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='vet_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
