# Generated by Django 3.0.3 on 2020-07-13 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='practice_license',
            new_name='practice_license1',
        ),
        migrations.AddField(
            model_name='registration',
            name='practice_license2',
            field=models.ImageField(blank=True, upload_to='%Y/%m/%d/'),
        ),
    ]
