# Generated by Django 3.0.3 on 2022-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='application_type',
            field=models.CharField(blank=True, choices=[('New Registration - Radiography Practice Permit', 'New Registration - Radiography Practice Permit'), ('New Registration - Private Hospital Internship', 'New Registration - Private Hospital Internship'), ('New Registration - Government Hospital Internship', 'New Registration - Government Hospital Internship'), ('Renewal - Radiography Practice Permit', 'Renewal - Radiography Practice Permit'), ('Renewal - Private Hospital Internship', 'Renewal - Private Hospital Internship'), ('Renewal - Government Hospital Internship', 'Renewal - Government Hospital Internship')], max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Bank', 'Bank')], max_length=100),
        ),
    ]
