# Generated by Django 3.0.3 on 2020-07-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20200713_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='inspection_scheduler',
            field=models.CharField(default='Ebere Onwuegbuchu', max_length=300),
        ),
    ]
