# Generated by Django 3.0.3 on 2020-05-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20200512_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='vet_status',
            field=models.IntegerField(default=1),
        ),
    ]
