# Generated by Django 3.0.3 on 2022-05-07 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20220503_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='submission_date',
            new_name='date',
        ),
    ]
