# Generated by Django 3.0.3 on 2020-09-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20200913_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='inspection_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
