# Generated by Django 3.0.3 on 2020-06-08 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20200608_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vet_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='vetting_officer',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
