# Generated by Django 3.0.3 on 2021-02-24 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_auto_20210224_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisal',
            name='inspection_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='inspection_report_deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='inspection_schedule_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='next_inspection_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
