# Generated by Django 3.0.3 on 2020-06-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_auto_20200608_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='inspection_scheduler',
            field=models.CharField(default='Ebere Onwuegbuchu', max_length=300),
        ),
    ]
