# Generated by Django 3.0.3 on 2022-05-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_auto_20220507_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='vet_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
