# Generated by Django 3.0.3 on 2021-02-25 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210224_2151'),
        ('hospitals', '0003_auto_20210224_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='address',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='email',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='inspection_date',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='inspection_report_deadline',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='inspection_schedule_date',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='inspection_zone',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='license_category',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='next_inspection_date',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='practice_manager',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='radiographers',
        ),
        migrations.RemoveField(
            model_name='appraisal',
            name='radiologists',
        ),
        migrations.AddField(
            model_name='appraisal',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_16', to='hospitals.Document'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_16', to='hospitals.Payment'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_16', to='hospitals.Schedule'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='vet_status',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='appraisal',
            name='hospital_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_16', to='accounts.Hospital'),
        ),
    ]
