# Generated by Django 3.0.3 on 2020-07-13 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_auto_20200713_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='radiographers',
            field=models.CharField(default='Malachy Owakwe', max_length=300),
        ),
    ]
