# Generated by Django 3.0.3 on 2020-06-08 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_auto_20200608_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='validity',
            new_name='license_status',
        ),
        migrations.AddField(
            model_name='license',
            name='last_inspection_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
