# Generated by Django 3.0.3 on 2020-07-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_auto_20200713_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='radiologists',
            field=models.CharField(blank=True, default='Malachy Owakwe', max_length=300, null=True),
        ),
    ]
