# Generated by Django 3.0.3 on 2021-02-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_auto_20210225_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='appraisal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_15', to='hospitals.Appraisal'),
        ),
    ]
