# Generated by Django 3.0.3 on 2020-09-17 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospitals', '0004_auto_20200913_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shielding_score', models.IntegerField()),
                ('room_design_score', models.IntegerField()),
                ('radiographers_no_score', models.IntegerField()),
                ('radiologists_no_score', models.IntegerField()),
                ('radiographer_license_score', models.IntegerField()),
                ('prmd_prpe_score', models.IntegerField()),
                ('water_supply_score', models.IntegerField()),
                ('equipment_certification_score', models.IntegerField()),
                ('accessories_adequacy_score', models.IntegerField()),
                ('warning_lights_score', models.IntegerField()),
                ('warning_signs_score', models.IntegerField()),
                ('C07_form_compliance_score', models.IntegerField()),
                ('equipment_installation_location_score', models.IntegerField()),
                ('processing_unit_score', models.IntegerField()),
                ('toilets_cleanliness_score', models.IntegerField()),
                ('waiting_room_score', models.IntegerField()),
                ('offices_adequacy_score', models.IntegerField()),
                ('carm_total', models.IntegerField()),
                ('practice_manager', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
