# Generated by Django 3.0.3 on 2024-11-19 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_auto_20241119_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='appraisal_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
