# Generated by Django 3.0.3 on 2020-06-08 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_auto_20200608_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='last_inspection_date',
            new_name='inspection_date',
        ),
    ]
