# Generated by Django 3.0.3 on 2020-07-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_auto_20200713_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='inspection_scheduler',
            field=models.CharField(max_length=300),
        ),
    ]
