# Generated by Django 3.0.3 on 2020-07-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_auto_20200713_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='vet_status',
            field=models.IntegerField(default=3),
        ),
    ]
