# Generated by Django 3.0.3 on 2020-06-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_auto_20200608_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='license_no',
            new_name='license_number',
        ),
    ]
