# Generated by Django 3.0.3 on 2024-12-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_appraisal_appraisal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='vet_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
