# Generated by Django 3.0.3 on 2020-07-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_schedule_vet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='radiologists',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
