# Generated by Django 3.0.3 on 2024-12-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_auto_20241201_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
