# Generated by Django 3.0.3 on 2020-06-08 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_auto_20200608_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='license_number',
        ),
    ]
