# Generated by Django 3.0.3 on 2020-06-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_remove_license_license_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='license_no',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
