# Generated by Django 3.0.3 on 2025-01-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0011_auto_20250103_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='zone',
            field=models.CharField(choices=[('Abuja', 'Abuja'), ('Enugu', 'Enugu'), ('Lagos', 'Lagos'), ('Sokoto', 'Sokoto'), ('Kano', 'Kano'), ('Port Harcourt', 'Port Harcourt'), ('Awka', 'Awka'), ('Calabar', 'Calabar'), ('Ilesha', 'Ilesha'), ('Maiduguri', 'Maiduguri')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
