# Generated by Django 3.0.3 on 2025-01-05 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0012_inspector_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='inspection_schedule_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
