# Generated by Django 3.0.3 on 2025-01-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0015_appraisal_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
