# Generated by Django 3.0.3 on 2025-01-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0016_auto_20250116_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_15', to='hospitals.Schedule'),
        ),
    ]
