# Generated by Django 3.0.3 on 2025-01-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0017_auto_20250118_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
