# Generated by Django 3.0.3 on 2025-01-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0018_inspection_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inspection',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
