# Generated by Django 3.0.3 on 2025-03-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0019_auto_20250120_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cac_certificate',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='form_c07',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='radiographer1_practice_license',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='radiographer2_practice_license',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='radiographer3_practice_license',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='radiographer_in_charge_nysc',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='radiographer_in_charge_passport',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='radiographer_in_charge_practice_license',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Card', 'Card')], max_length=100),
        ),
    ]
