# Generated by Django 3.0.3 on 2025-05-07 11:21

from django.db import migrations, models
import hospitals.models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0020_auto_20250323_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='radiographer_in_charge_passport',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d/', validators=[hospitals.models.validate_image_file_extension]),
        ),
    ]
