# Generated by Django 3.0.3 on 2025-05-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0021_auto_20250507_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisal',
            name='inspection_report',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_report',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/'),
        ),
    ]
