# Generated by Django 3.0.3 on 2025-07-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0022_auto_20250515_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='license_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
