# Generated by Django 3.0.3 on 2025-08-06 15:30

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0025_auto_20250806_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='equipment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Ultrasound', 'Ultrasound'), ('Conventional X-ray', 'Conventional X-ray'), ('Fluoroscopy', 'Fluoroscopy'), ('CT Scan', 'CT Scan'), ('C-Arm/O-ARM', 'C-Arm/O-ARM'), ('MRI', 'MRI'), ('Mamography', 'Mamography'), ('Angiography', 'Angiography'), ('Dental X-ray', 'Dental X-ray'), ('Echocardiography', 'Echocardiography'), ('Radiotherapy', 'Radiotherapy'), ('Nuclear Medicine', 'Nuclear Medicine')], max_length=255),
        ),
    ]
